export const bookingModalInlineStyles: Record<string, (...args: any[]) => any> = {
  s1: ({ isMobile }: any) => ({
        backgroundColor: "#141414",
        paddingHorizontal: 12,
        paddingVertical: isMobile ? 10 : 12,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: "#007c00",
        flexDirection: "row",
        alignItems: "center"
      }),
  s2: ({ isMobile, value }: any) => ({
          flex: 1,
          color: value ? "#fff" : "#666",
          fontSize: isMobile ? 12 : 14,
          fontWeight: "600",
          padding: 0
        }),
  s3: () => ({ color: "#f5f2e8", fontSize: 16, marginLeft: 8 }),
  s4: () => ({ flex: 1, backgroundColor: "#0b0b0b" }),
  s5: () => ({ flex: 1 }),
  s6: ({ Platform, isMobile }: any) => ({
            padding: isMobile ? 14 : 18,
            paddingTop: Platform.select({ ios: 48, default: isMobile ? 14 : 18 })
          }),
  s7: () => ({ flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 8 }),
  s8: ({ isMobile }: any) => ({ color: "#fff", fontSize: isMobile ? 16 : 18, fontWeight: "700", flex: 1, marginRight: 12 }),
  s9: ({ isMobile }: any) => ({
                backgroundColor: "#007c00",
                borderRadius: 999,
                paddingHorizontal: isMobile ? 12 : 14,
                paddingVertical: isMobile ? 6 : 7,
                minWidth: isMobile ? 84 : 96,
                alignItems: "center",
                justifyContent: "center"
              }),
  s10: ({ isMobile }: any) => ({ color: "#fff", fontSize: isMobile ? 14 : 16, fontWeight: "800" }),
  s11: ({ isMobile }: any) => ({ color: "#aaa", fontSize: isMobile ? 12 : 14 }),
  s12: ({ isMobile }: any) => ({
            marginTop: 16,
            gap: 16,
            flexDirection: isMobile ? "column" : "row"
          }),
  s13: ({ isMobile }: any) => ({
              flex: 1,
              borderWidth: 1,
              borderColor: "#1f1f1f",
              borderRadius: 14,
              padding: isMobile ? 12 : 14,
              backgroundColor: "#0f0f0f"
            }),
  s14: () => ({ color: "#fff", fontSize: 16, fontWeight: "700" }),
  s15: () => ({ marginTop: 8 }),
  s16: ({ isMobile }: any) => ({ color: "#fff", fontSize: isMobile ? 18 : 20, fontWeight: "800" }),
  s17: ({ isMobile }: any) => ({ color: "#aaa", marginTop: 6, fontSize: isMobile ? 12 : 14 }),
  s18: ({ isMobile }: any) => ({ color: "#aaa", marginTop: 6, fontSize: isMobile ? 12 : 14 }),
  s19: ({ isMobile }: any) => ({ color: "#aaa", marginTop: 4, fontSize: isMobile ? 12 : 14 }),
  s20: ({ isMobile }: any) => ({ color: "#f5f2e8", fontWeight: "800", marginTop: 8, fontSize: isMobile ? 16 : 18 }),
  s21: () => ({ marginTop: 10, marginBottom: 12 }),
  s22: () => ({ position: "relative", marginBottom: 10 }),
  s23: ({ mainImageHeight }: any) => ({
                          width: "100%",
                          height: mainImageHeight,
                          borderRadius: 12,
                          backgroundColor: "#111",
                          borderWidth: 1,
                          borderColor: "#333"
                        }),
  s24: () => ({
                          position: "absolute",
                          top: 0,
                          left: 0,
                          right: 0,
                          bottom: 0,
                          backgroundColor: "#1a1a1a",
                          alignItems: "center",
                          justifyContent: "center",
                          borderRadius: 12
                        }),
  s25: () => ({ color: "#666", fontSize: 16, fontWeight: "700", letterSpacing: 1 }),
  s26: () => ({ color: "#555", fontSize: 12, marginTop: 4 }),
  s27: () => ({ marginBottom: 10, paddingHorizontal: 4 }),
  s28: ({ isMobile }: any) => ({ color: "#fff", fontWeight: "800", fontSize: isMobile ? 14 : 16 }),
  s29: ({ isMobile }: any) => ({ color: "#aaa", marginTop: 4, fontSize: isMobile ? 12 : 14 }),
  s30: ({ thumbnailHeight }: any) => ({ minHeight: thumbnailHeight + 4 }),
  s31: () => ({ cursor: "pointer" }),
  s32: () => ({ position: "relative" }),
  s33: ({ img, selectedImage, thumbnailHeight, thumbnailWidth }: any) => ({
                            width: thumbnailWidth,
                            height: thumbnailHeight,
                            borderRadius: 8,
                            backgroundColor: "#111",
                            borderWidth: 2,
                            borderColor: selectedImage === img.src ? "#f5f2e8" : "#333",
                          }),
  s34: () => ({
                            position: "absolute",
                            top: 0,
                            left: 0,
                            right: 0,
                            bottom: 0,
                            backgroundColor: "#1a1a1a",
                            alignItems: "center",
                            justifyContent: "center",
                            borderRadius: 8,
                            pointerEvents: "none"
                          }),
  s35: () => ({ color: "#666", fontSize: 10, fontWeight: "700" }),
  s36: () => ({ color: "#555", fontSize: 8, marginTop: 2 }),
  s37: () => ({
                  marginTop: 12,
                  borderWidth: 1,
                  borderColor: "#1f1f1f",
                  borderRadius: 12,
                  backgroundColor: "#101010",
                  padding: 10
                }),
  s38: ({ isMobile }: any) => ({ flexDirection: isMobile ? "column" : "row", gap: 10 }),
  s39: () => ({ flex: 1, backgroundColor: "#151515", borderRadius: 10, padding: 10, borderWidth: 1, borderColor: "#202020" }),
  s40: ({ isMobile }: any) => ({ color: "#fff", fontWeight: "700", fontSize: isMobile ? 13 : 14 }),
  s41: ({ isMobile }: any) => ({ color: "#aaa", marginTop: 4, fontSize: isMobile ? 11 : 12 }),
  s42: ({ isMobile }: any) => ({ color: "#666", marginTop: 4, fontSize: isMobile ? 11 : 12 }),
  s43: () => ({ flex: 1, backgroundColor: "#151515", borderRadius: 10, padding: 10, borderWidth: 1, borderColor: "#202020" }),
  s44: ({ isMobile }: any) => ({ color: "#fff", fontWeight: "700", fontSize: isMobile ? 13 : 14 }),
  s45: ({ isMobile }: any) => ({ color: "#aaa", marginTop: 4, fontSize: isMobile ? 11 : 12 }),
  s46: ({ isMobile }: any) => ({ color: "#666", marginTop: 4, fontSize: isMobile ? 11 : 12 }),
  s47: () => ({ flex: 1, backgroundColor: "#151515", borderRadius: 10, padding: 10, borderWidth: 1, borderColor: "#202020" }),
  s48: ({ isMobile }: any) => ({ color: "#fff", fontWeight: "700", fontSize: isMobile ? 13 : 14 }),
  s49: ({ isMobile }: any) => ({ color: "#aaa", marginTop: 4, fontSize: isMobile ? 11 : 12 }),
  s50: ({ isMobile }: any) => ({ color: "#666", marginTop: 4, fontSize: isMobile ? 11 : 12 }),
  s51: () => ({ marginTop: 12 }),
  s52: ({ isMobile }: any) => ({ color: "#fff", fontWeight: "700", fontSize: isMobile ? 14 : 16 }),
  s53: () => ({ flexDirection: "row", alignItems: "flex-start", marginTop: 6, gap: 8 }),
  s54: ({ isMobile }: any) => ({ color: "#f5f2e8", fontSize: isMobile ? 14 : 15, marginTop: 1 }),
  s55: ({ isMobile }: any) => ({ color: "#aaa", fontSize: isMobile ? 12 : 14, flex: 1 }),
  s56: () => ({ marginTop: 12 }),
  s57: ({ isMobile }: any) => ({ color: "#fff", fontWeight: "700", fontSize: isMobile ? 14 : 16, marginBottom: 10 }),
  s58: () => ({ position: "relative" }),
  s59: () => ({ color: "#fff", fontSize: 20, fontWeight: "700" }),
  s60: ({ isMobile }: any) => ({
                            minWidth: isMobile ? 130 : 155,
                            backgroundColor: "#141414",
                            borderWidth: 1,
                            borderColor: "#1f1f1f",
                            borderRadius: 12,
                            padding: 10,
                            paddingTop: 8,
                            justifyContent: "flex-start",
                            minHeight: isMobile ? 86 : 96,
                            shadowColor: "#000",
                            shadowOffset: { width: 0, height: 2 },
                            shadowOpacity: 0.3,
                            shadowRadius: 4,
                            elevation: 3
                          }),
  s61: ({ isMobile }: any) => ({
                                color: "#f5f2e8",
                                fontWeight: "800",
                                fontSize: isMobile ? 10 : 11,
                                letterSpacing: 1,
                                marginBottom: 4,
                                textTransform: "uppercase"
                              }),
  s62: ({ isMobile }: any) => ({
                                color: "#fff",
                                fontWeight: "600",
                                fontSize: isMobile ? 11 : 12,
                                lineHeight: 16,
                                marginBottom: 6
                              }),
  s63: ({ isMobile }: any) => ({
                                color: "#aaa",
                                fontWeight: "400",
                                fontSize: isMobile ? 10 : 11,
                                lineHeight: 14
                              }),
  s64: () => ({ color: "#fff", fontSize: 20, fontWeight: "700" }),
  s65: () => ({ marginTop: 12 }),
  s66: ({ isMobile }: any) => ({ color: "#fff", fontWeight: "700", fontSize: isMobile ? 14 : 16, marginBottom: 8 }),
  s67: () => ({ flexDirection: "row", flexWrap: "wrap", gap: 12 }),
  s68: () => ({ flexDirection: "row", alignItems: "center", gap: 6 }),
  s69: ({ isMobile }: any) => ({ color: "#f5f2e8", fontSize: isMobile ? 14 : 15 }),
  s70: ({ isMobile }: any) => ({ color: "#aaa", fontSize: isMobile ? 12 : 14 }),
  s71: ({ isMobile }: any) => ({
              flex: 1,
              borderWidth: 1,
              borderColor: "#1f1f1f",
              borderRadius: 14,
              padding: isMobile ? 12 : 14,
              backgroundColor: "#0f0f0f"
            }),
  s72: () => ({ color: "#fff", fontSize: 16, fontWeight: "700", marginBottom: 12 }),
  s73: () => ({ marginTop: 8, gap: 12 }),
  s74: () => ({ backgroundColor: "#0a0a0a", borderRadius: 10, padding: 12, borderLeftWidth: 3, borderLeftColor: "#007c00" }),
  s75: () => ({ color: "#f5f2e8", fontSize: 12, fontWeight: "700", marginBottom: 10, textTransform: "uppercase", letterSpacing: 0.5 }),
  s76: () => ({ marginTop: 8 }),
  s77: () => ({ marginTop: 8 }),
  s78: () => ({ backgroundColor: "#0a0a0a", borderRadius: 10, padding: 12, borderLeftWidth: 3, borderLeftColor: "#007c00" }),
  s79: () => ({ color: "#f5f2e8", fontSize: 12, fontWeight: "700", marginBottom: 8, textTransform: "uppercase", letterSpacing: 0.5 }),
  s80: () => ({ marginBottom: 10 }),
  s81: ({ isMobile }: any) => ({ color: "#ddd", marginBottom: 8, fontSize: isMobile ? 12 : 14, fontWeight: "600" }),
  s82: () => ({ borderRadius: 8, borderWidth: 1, borderColor: "#222", backgroundColor: "#141414", overflow: "hidden" }),
  s83: ({ i, item, roomType, rt }: any) => ({
                                  paddingHorizontal: 12,
                                  paddingVertical: 10,
                                  borderBottomWidth: i < item.raw.roomTypes.length - 1 ? 1 : 0,
                                  borderBottomColor: "#222",
                                  backgroundColor: roomType === rt.type ? "#1a3a1a" : "transparent"
                                }),
  s84: ({ isMobile, roomType, rt }: any) => ({ color: roomType === rt.type ? "#f5f2e8" : "#aaa", fontWeight: roomType === rt.type ? "700" : "500", fontSize: isMobile ? 12 : 14 }),
  s85: ({ isMobile }: any) => ({ color: "#ddd", marginBottom: 8, fontSize: isMobile ? 12 : 14, fontWeight: "600" }),
  s86: () => ({ flexDirection: "row", alignItems: "center", gap: 8 }),
  s87: () => ({
                                backgroundColor: "#007c00",
                                width: 36,
                                height: 36,
                                borderRadius: 6,
                                alignItems: "center",
                                justifyContent: "center"
                              }),
  s88: () => ({ color: "#fff", fontSize: 18, fontWeight: "700" }),
  s89: () => ({ color: "#fff", fontSize: 16, fontWeight: "700", flex: 1, textAlign: "center", backgroundColor: "#141414", paddingVertical: 8, borderRadius: 6 }),
  s90: () => ({
                                backgroundColor: "#007c00",
                                width: 36,
                                height: 36,
                                borderRadius: 6,
                                alignItems: "center",
                                justifyContent: "center"
                              }),
  s91: () => ({ color: "#fff", fontSize: 18, fontWeight: "700" }),
  s92: () => ({ backgroundColor: "#0a0a0a", borderRadius: 10, padding: 12, borderLeftWidth: 3, borderLeftColor: "#007c00" }),
  s93: () => ({ color: "#f5f2e8", fontSize: 12, fontWeight: "700", marginBottom: 8, textTransform: "uppercase", letterSpacing: 0.5 }),
  s94: () => ({ flexDirection: "row", flexWrap: "wrap", gap: 8 }),
  s95: ({ tier, tierName }: any) => ({
                                paddingHorizontal: 10,
                                paddingVertical: 8,
                                borderRadius: 8,
                                borderWidth: 1,
                                borderColor: tierName === tier.name ? "#007c00" : "#222",
                                backgroundColor: tierName === tier.name ? "#1a3a1a" : "#141414"
                              }),
  s96: ({ isMobile }: any) => ({ color: "#f5f2e8", fontSize: isMobile ? 12 : 13, fontWeight: "700" }),
  s97: () => ({ color: "#777", fontSize: 11, marginTop: 6 }),
  s98: () => ({ backgroundColor: "#0a0a0a", borderRadius: 10, padding: 12, borderLeftWidth: 3, borderLeftColor: "#007c00" }),
  s99: () => ({ color: "#f5f2e8", fontSize: 12, fontWeight: "700", marginBottom: 12, textTransform: "uppercase", letterSpacing: 0.5 }),
  s100: () => ({ flexDirection: "row", gap: 10 }),
  s101: () => ({ flex: 1 }),
  s102: ({ isMobile }: any) => ({ color: "#ddd", marginBottom: 6, fontSize: isMobile ? 12 : 14, fontWeight: "600" }),
  s103: ({ isMobile }: any) => ({
                                  backgroundColor: "#141414",
                                  paddingHorizontal: 12,
                                  paddingVertical: isMobile ? 10 : 12,
                                  borderRadius: 8,
                                  borderWidth: 1,
                                  borderColor: "#007c00",
                                  flexDirection: "row",
                                  alignItems: "center",
                                  justifyContent: "space-between"
                                }),
  s104: ({ isMobile }: any) => ({ color: "#fff", fontSize: isMobile ? 12 : 14, fontWeight: "600" }),
  s105: () => ({ color: "#f5f2e8", fontSize: 16 }),
  s106: () => ({ flex: 1 }),
  s107: ({ isMobile }: any) => ({ color: "#ddd", marginBottom: 6, fontSize: isMobile ? 12 : 14, fontWeight: "600" }),
  s108: ({ isMobile }: any) => ({
                                  backgroundColor: "#141414",
                                  paddingHorizontal: 12,
                                  paddingVertical: isMobile ? 10 : 12,
                                  borderRadius: 8,
                                  borderWidth: 1,
                                  borderColor: "#007c00",
                                  flexDirection: "row",
                                  alignItems: "center",
                                  justifyContent: "space-between"
                                }),
  s109: ({ isMobile }: any) => ({ color: "#fff", fontSize: isMobile ? 12 : 14, fontWeight: "600" }),
  s110: () => ({ color: "#f5f2e8", fontSize: 16 }),
  s111: () => ({ marginTop: 10, backgroundColor: "#141414", borderRadius: 6, padding: 8 }),
  s112: () => ({ color: "#aaa", fontSize: 12 }),
  s113: () => ({ color: "#f5f2e8", fontWeight: "700" }),
  s114: () => ({ marginTop: 8, backgroundColor: "#1a1a1a", borderRadius: 6, padding: 8, borderWidth: 1, borderColor: "#333" }),
  s115: () => ({ color: "#ffb4b4", fontSize: 12, fontWeight: "700" }),
  s116: () => ({ marginTop: 8 }),
  s117: () => ({ color: "#aaa", fontSize: 12 }),
  s118: () => ({ color: "#f5f2e8", fontWeight: "700" }),
  s119: () => ({ marginTop: 8 }),
  s120: () => ({ color: "#aaa", fontSize: 12 }),
  s121: () => ({ color: "#aaa", fontSize: 12 }),
  s122: () => ({ color: "#777", fontSize: 11, marginTop: 4 }),
  s123: () => ({ backgroundColor: "#0a0a0a", borderRadius: 10, padding: 12, borderLeftWidth: 3, borderLeftColor: "#007c00" }),
  s124: () => ({ color: "#f5f2e8", fontSize: 12, fontWeight: "700", marginBottom: 10, textTransform: "uppercase", letterSpacing: 0.5 }),
  s125: () => ({ color: "#aaa", fontSize: 12, marginBottom: 8 }),
  s126: () => ({ flexDirection: "row", alignItems: "center", gap: 8 }),
  s127: () => ({
                            backgroundColor: "#007c00",
                            width: 36,
                            height: 36,
                            borderRadius: 6,
                            alignItems: "center",
                            justifyContent: "center"
                          }),
  s128: () => ({ color: "#fff", fontSize: 18, fontWeight: "700" }),
  s129: () => ({ color: "#fff", fontSize: 16, fontWeight: "700", flex: 1, textAlign: "center", backgroundColor: "#141414", paddingVertical: 8, borderRadius: 6 }),
  s130: () => ({
                            backgroundColor: "#007c00",
                            width: 36,
                            height: 36,
                            borderRadius: 6,
                            alignItems: "center",
                            justifyContent: "center"
                          }),
  s131: () => ({ color: "#fff", fontSize: 18, fontWeight: "700" }),
  s132: () => ({ backgroundColor: "#0a0a0a", borderRadius: 10, padding: 12, borderLeftWidth: 3, borderLeftColor: "#007c00" }),
  s133: () => ({ color: "#f5f2e8", fontSize: 12, fontWeight: "700", marginBottom: 10, textTransform: "uppercase", letterSpacing: 0.5 }),
  s134: ({ isMobile }: any) => ({ color: "#ddd", marginBottom: 6, fontSize: isMobile ? 12 : 14, fontWeight: "600" }),
  s135: ({ isMobile }: any) => ({
                            backgroundColor: "#141414",
                            paddingHorizontal: 12,
                            paddingVertical: isMobile ? 10 : 12,
                            borderRadius: 8,
                            borderWidth: 1,
                            borderColor: "#007c00",
                            flexDirection: "row",
                            alignItems: "center",
                            justifyContent: "space-between"
                          }),
  s136: ({ isMobile }: any) => ({ color: "#fff", fontSize: isMobile ? 12 : 14, fontWeight: "600" }),
  s137: () => ({ color: "#f5f2e8", fontSize: 16 }),
  s138: () => ({ marginTop: 8, backgroundColor: "#1a1a1a", borderRadius: 6, padding: 8, borderWidth: 1, borderColor: "#333" }),
  s139: () => ({ color: "#ffb4b4", fontSize: 12, fontWeight: "700" }),
  s140: () => ({ marginTop: 8 }),
  s141: () => ({ color: "#aaa", fontSize: 12 }),
  s142: () => ({ color: "#f5f2e8", fontWeight: "700" }),
  s143: ({ isMobile }: any) => ({ color: "#ddd", marginTop: 10, marginBottom: 6, fontSize: isMobile ? 12 : 14, fontWeight: "600" }),
  s144: () => ({ flexDirection: "row", alignItems: "center", gap: 8 }),
  s145: () => ({
                          backgroundColor: "#007c00",
                          width: 36,
                          height: 36,
                          borderRadius: 6,
                          alignItems: "center",
                          justifyContent: "center"
                        }),
  s146: () => ({ color: "#fff", fontSize: 18, fontWeight: "700" }),
  s147: () => ({ color: "#fff", fontSize: 16, fontWeight: "700", flex: 1, textAlign: "center", backgroundColor: "#141414", paddingVertical: 8, borderRadius: 6 }),
  s148: () => ({
                          backgroundColor: "#007c00",
                          width: 36,
                          height: 36,
                          borderRadius: 6,
                          alignItems: "center",
                          justifyContent: "center"
                        }),
  s149: () => ({ color: "#fff", fontSize: 18, fontWeight: "700" }),
  s150: () => ({ backgroundColor: "#0a0a0a", borderRadius: 10, padding: 12, borderLeftWidth: 3, borderLeftColor: "#007c00" }),
  s151: () => ({ color: "#f5f2e8", fontSize: 12, fontWeight: "700", marginBottom: 8, textTransform: "uppercase", letterSpacing: 0.5 }),
  s152: () => ({ color: "#aaa", fontSize: 12, marginBottom: 8 }),
  s153: () => ({ flexDirection: "row", alignItems: "center", gap: 8, flexWrap: "wrap" }),
  s154: () => ({
                        backgroundColor: "#f5f2e8",
                        paddingHorizontal: 12,
                        paddingVertical: 8,
                        borderRadius: 8
                      }),
  s155: () => ({ color: "#111", fontWeight: "800", fontSize: 12 }),
  s156: () => ({ color: "#9ef1a6", fontSize: 12, fontWeight: "700" }),
  s157: () => ({ color: "#aaa", fontSize: 12 }),
  s158: () => ({ color: "#ff6b6b", fontSize: 12, marginTop: 6 }),
  s159: () => ({ backgroundColor: "#0a0a0a", borderRadius: 10, padding: 12, borderLeftWidth: 3, borderLeftColor: "#007c00" }),
  s160: () => ({ color: "#f5f2e8", fontSize: 12, fontWeight: "700", marginBottom: 8, textTransform: "uppercase", letterSpacing: 0.5 }),
  s161: ({ isMobile }: any) => ({
                      backgroundColor: "#141414",
                      color: "#fff",
                      paddingHorizontal: 12,
                      paddingVertical: 10,
                      borderRadius: 8,
                      borderWidth: 1,
                      borderColor: "#222",
                      fontSize: isMobile ? 12 : 14,
                      textAlignVertical: "top"
                    }),
  s162: () => ({ backgroundColor: "#0a0a0a", borderRadius: 10, padding: 12, borderLeftWidth: 3, borderLeftColor: "#007c00" }),
  s163: () => ({ color: "#f5f2e8", fontSize: 12, fontWeight: "700", marginBottom: 8, textTransform: "uppercase", letterSpacing: 0.5 }),
  s164: () => ({ marginBottom: 8, gap: 6 }),
  s165: () => ({ color: "#aaa", fontSize: 12, fontWeight: "600" }),
  s166: () => ({ color: "#ddd", fontSize: 12 }),
  s167: () => ({ gap: 4 }),
  s168: () => ({ color: "#aaa", fontSize: 12, fontWeight: "600" }),
  s169: () => ({ color: "#ddd", fontSize: 12 }),
  s170: () => ({ color: "#ddd", fontSize: 12 }),
  s171: ({ isMobile }: any) => ({ color: "#ff6b6b", marginTop: 12, fontSize: isMobile ? 12 : 14, fontWeight: "600" }),
  s172: ({ isMobile }: any) => ({ color: "#9ef1a6", marginTop: 12, fontSize: isMobile ? 12 : 14, fontWeight: "600" }),
  s173: () => ({
                  marginTop: 14,
                  backgroundColor: "#007c00",
                  borderRadius: 10,
                  padding: 14,
                  shadowColor: "#000",
                  shadowOffset: { width: 0, height: 4 },
                  shadowOpacity: 0.3,
                  shadowRadius: 8,
                  elevation: 8
                }),
  s174: () => ({ color: "#fff", fontSize: 12, fontWeight: "700", marginBottom: 10, textTransform: "uppercase", letterSpacing: 0.5 }),
  s175: () => ({ gap: 8, marginBottom: 10 }),
  s176: () => ({ flexDirection: "row", justifyContent: "space-between" }),
  s177: ({ isMobile }: any) => ({ color: "#f5f2e8", fontSize: isMobile ? 12 : 13 }),
  s178: ({ isMobile }: any) => ({ color: "#f5f2e8", fontSize: isMobile ? 12 : 13, fontWeight: "600" }),
  s179: () => ({ flexDirection: "row", justifyContent: "space-between" }),
  s180: ({ isMobile }: any) => ({ color: "#f5f2e8", fontSize: isMobile ? 12 : 13 }),
  s181: ({ isMobile }: any) => ({ color: "#f5f2e8", fontSize: isMobile ? 12 : 13, fontWeight: "600" }),
  s182: () => ({ flexDirection: "row", justifyContent: "space-between" }),
  s183: ({ isMobile }: any) => ({ color: "#f5f2e8", fontSize: isMobile ? 12 : 13 }),
  s184: ({ isMobile }: any) => ({ color: "#f5f2e8", fontSize: isMobile ? 12 : 13, fontWeight: "600" }),
  s185: () => ({ borderTopWidth: 1, borderTopColor: "#f5f2e8", paddingTop: 10 }),
  s186: () => ({ flexDirection: "row", justifyContent: "space-between", alignItems: "center" }),
  s187: ({ isMobile }: any) => ({ color: "#fff", fontSize: isMobile ? 14 : 16, fontWeight: "700" }),
  s188: () => ({ color: "#e7ffe7", fontSize: 11 }),
  s189: ({ isMobile }: any) => ({ color: "#fff", fontSize: isMobile ? 24 : 28, fontWeight: "900" }),
  s190: ({ hovered, isMobile }: any) => ({ fontWeight: "800", fontSize: isMobile ? 14 : 16, color: hovered ? "#fff" : "#1c1c1c" }),
  s191: () => ({
            position: "absolute",
            top: 0,
            left: 0,
            right: 0,
            bottom: 0,
            backgroundColor: "rgba(0,0,0,0.6)",
            alignItems: "center",
            justifyContent: "center",
            zIndex: 1000
          }),
  s192: ({ isMobile }: any) => ({
              backgroundColor: "#0f0f0f",
              borderRadius: 12,
              borderWidth: 1,
              borderColor: "#1f1f1f",
              padding: 14,
              width: isMobile ? "90%" : 360
            }),
  s193: () => ({ flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 10 }),
  s194: () => ({ padding: 6, borderRadius: 6, backgroundColor: "#1a1a1a" }),
  s195: () => ({ color: "#fff", fontSize: 16 }),
  s196: () => ({ color: "#fff", fontSize: 14, fontWeight: "700" }),
  s197: () => ({ padding: 6, borderRadius: 6, backgroundColor: "#1a1a1a" }),
  s198: () => ({ color: "#fff", fontSize: 16 }),
  s199: () => ({ flexDirection: "row", flexWrap: "wrap" }),
  s200: () => ({ width: "14.285%", alignItems: "center", marginBottom: 6 }),
  s201: () => ({ color: "#777", fontSize: 11, fontWeight: "700" }),
  s202: () => ({ width: "14.285%", height: 32 }),
  s203: ({ disabled }: any) => ({
                          width: "14.285%",
                          height: 32,
                          alignItems: "center",
                          justifyContent: "center",
                          opacity: disabled ? 0.35 : 1
                        }),
  s204: ({ disabled }: any) => ({ color: disabled ? "#555" : "#fff", fontSize: 12 }),
  s205: () => ({ marginTop: 10, paddingVertical: 8, borderRadius: 8, backgroundColor: "#1a1a1a", alignItems: "center" }),
  s206: () => ({ color: "#fff", fontWeight: "700" }),
  s207: ({ isMobile }: any) => ({ color: "#ddd", marginBottom: 6, fontSize: isMobile ? 12 : 14, fontWeight: "600" }),
  s208: ({ isMobile }: any) => ({
          backgroundColor: "#141414",
          color: "#fff",
          paddingHorizontal: 12,
          paddingVertical: isMobile ? 10 : 12,
          borderRadius: 8,
          borderWidth: 1,
          borderColor: "#222",
          fontSize: isMobile ? 14 : 16
        }),
  s209: () => ({ gap: 8, paddingRight: 16, paddingLeft: 4, flexGrow: 1 }),
  s210: (side: "left" | "right", hovered: boolean) => ({
    position: "absolute",
    left: side === "left" ? 0 : undefined,
    right: side === "right" ? 0 : undefined,
    top: "50%",
    zIndex: 10,
    marginTop: -20,
    backgroundColor: "#007c00",
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    opacity: hovered ? 0.8 : 1,
  }),
  s211: () => ({ paddingRight: 8, gap: 10, paddingHorizontal: 50 }),
  s212: () => ({ fontWeight: "bold" }),
  s213: ({ isMobile, hovered, busy }: any) => ({
    marginTop: 16,
    backgroundColor: hovered ? "#007c00" : "#fff",
    paddingVertical: isMobile ? 12 : 14,
    borderRadius: 10,
    alignItems: "center",
    opacity: busy ? 0.6 : 1,
    shadowColor: "#007c00",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: hovered ? 0.4 : 0.2,
    shadowRadius: 8,
    elevation: 5,
  }),
};

export const bookingModalColors = {
  placeholder: "#666",
} as const;
