import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  flexTransparent: { flex: 1, backgroundColor: "transparent" },
  flexOnly: { flex: 1 },
  centerWrap: { flex: 1, alignItems: "center", justifyContent: "center" },
  centerWrapPadded: { flex: 1, alignItems: "center", justifyContent: "center", padding: 20, backgroundColor: "transparent" },
  loadingTextBase: { color: "#54607a", marginTop: 16 },
  errorTextBase: { color: "#ff6b6b", fontWeight: "700", marginBottom: 16, textAlign: "center" },
  retryTextBase: { color: "#fff", fontWeight: "700" },
  vendorsContainerBase: { backgroundColor: "#0f1a2d", borderRadius: 18, borderWidth: 1, borderColor: "#1d3258" },
  vendorsKicker: { color: "#eaf2ff", fontSize: 12, letterSpacing: 1.2, marginBottom: 6 },
  vendorsTitleBase: { color: "#fff", fontWeight: "800" },
  vendorsSubBase: { color: "#9db0d6" },
  placeCardBase: { gap: 8, backgroundColor: "#fff", borderWidth: 1, borderColor: "#dbe3ef", borderRadius: 16 },
  placeTitleBase: { color: "#5f6b81", fontWeight: "700" },
  rowWrap: { flexDirection: "row", gap: 8, flexWrap: "wrap" },
  placePillTextBase: { fontWeight: "700" },
  searchInputBase: { backgroundColor: "#fff", color: "#111827", paddingHorizontal: 14, borderRadius: 12, borderWidth: 1, borderColor: "#d5deeb" },
  emptyStatePad: { padding: 40, alignItems: "center" },
  emptyStateTextBase: { color: "#7b8798", textAlign: "center" },
  vendorGridBase: { flexDirection: "row", flexWrap: "wrap" },
  menuHeaderBase: { backgroundColor: "#ffffff", borderBottomWidth: 1, borderBottomColor: "#dce3ef" },
  rowCenterGap12: { flexDirection: "row", alignItems: "center", gap: 12 },
  backArrowTextBase: { color: "#374151" },
  menuTitleBase: { color: "#111827", fontWeight: "700" },
  menuSubBase: { color: "#6b7280" },
  smallMetaText: { color: "#7c8698", fontSize: 11 },
  smallMetaTextTight: { color: "#7c8698", fontSize: 11, marginTop: 2 },
  menuCategoriesRow: { flexDirection: "row", gap: 8 },
  categoryTextBase: { fontWeight: "700" },
  menuListPadBase: { paddingBottom: 100 },
  emptyMenuTextBase: { color: "#666", textAlign: "center" },
  checkoutTitleBase: { color: "#111827", fontWeight: "800" },
  orderCardBase: { backgroundColor: "#ffffff", borderRadius: 12, borderWidth: 1, borderColor: "#d5deeb" },
  orderCardTitleBase: { color: "#111827", fontWeight: "700" },
  orderItemRow: { flexDirection: "row", justifyContent: "space-between", paddingVertical: 8 },
  orderItemNameBase: { color: "#111827" },
  orderItemPriceBase: { color: "#f4511e", fontWeight: "700" },
  successIconWrapBase: { backgroundColor: "#d7f6de", alignItems: "center", justifyContent: "center", marginBottom: 24 },
  successTitleBase: { color: "#111827", fontWeight: "800", marginBottom: 12, textAlign: "center" },
  successSubtitleBase: { color: "#667085", textAlign: "center", marginBottom: 8 },
  successOrderIdWrap: { backgroundColor: "#ffffff", paddingHorizontal: 20, paddingVertical: 12, borderRadius: 8, borderWidth: 1, borderColor: "#d5deeb", marginBottom: 32 },
  successOrderIdTextBase: { color: "#f4511e", fontWeight: "700" },
  successEtaBase: { color: "#54607a", textAlign: "center", marginBottom: 32 },
  orderMoreTextBase: { color: "#fff", fontWeight: "800" },
});

export const ds = {
  loadingText: (isMobile: boolean) => [styles.loadingTextBase, { fontSize: isMobile ? 14 : 16 }],
  errorText: (isMobile: boolean) => [styles.errorTextBase, { fontSize: isMobile ? 16 : 18 }],
  retryText: (isMobile: boolean) => [styles.retryTextBase, { fontSize: isMobile ? 14 : 16 }],
  retryBtn: (hovered: boolean) => ({ backgroundColor: hovered ? "#d73f11" : "#f4511e", paddingHorizontal: 24, paddingVertical: 12, borderRadius: 8 }),
  sectionPad: (isMobile: boolean, tight = false) => ({ padding: isMobile ? 14 : 20, gap: isMobile ? (tight ? 16 : 20) : tight ? 20 : 24 }),
  heroCard: (isMobile: boolean) => [styles.vendorsContainerBase, { padding: isMobile ? 14 : 18 }],
  heroTitle: (isMobile: boolean) => [styles.vendorsTitleBase, { fontSize: isMobile ? 22 : 28, marginBottom: isMobile ? 8 : 12 }],
  heroSub: (isMobile: boolean) => [styles.vendorsSubBase, { fontSize: isMobile ? 13 : 15 }],
  placeCard: (isMobile: boolean) => [styles.placeCardBase, { padding: isMobile ? 12 : 14 }],
  placeTitle: (isMobile: boolean) => [styles.placeTitleBase, { fontSize: isMobile ? 13 : 14 }],
  placePill: (active: boolean) => ({
    backgroundColor: active ? "#f4511e" : "#f7f9fc",
    borderWidth: 1,
    borderColor: active ? "#f4511e" : "#d5deeb",
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 9,
  }),
  placePillText: (active: boolean) => [styles.placePillTextBase, { color: active ? "#fff" : "#334155" }],
  searchInput: (isMobile: boolean, compact = false) => [styles.searchInputBase, { paddingVertical: compact ? (isMobile ? 10 : 12) : isMobile ? 12 : 14, fontSize: isMobile ? 14 : 16 }],
  emptyStateText: (isMobile: boolean) => [styles.emptyStateTextBase, { fontSize: isMobile ? 14 : 16 }],
  vendorGrid: (gridGap: number) => [styles.vendorGridBase, { gap: gridGap }],
  vendorWidth: (vendorCardWidth: string | number) => ({ width: vendorCardWidth }),
  menuHeader: (isMobile: boolean) => [styles.menuHeaderBase, { padding: isMobile ? 14 : 18, gap: isMobile ? 12 : 14 }],
  backBtn: (hovered: boolean) => ({ backgroundColor: hovered ? "#e9eef6" : "#f4f7fb", paddingHorizontal: 12, paddingVertical: 8, borderRadius: 8, borderWidth: 1, borderColor: "#d7dfec" }),
  backArrowText: (isMobile: boolean) => [styles.backArrowTextBase, { fontSize: isMobile ? 16 : 18 }],
  menuTitle: (isMobile: boolean) => [styles.menuTitleBase, { fontSize: isMobile ? 18 : 20 }],
  menuSub: (isMobile: boolean) => [styles.menuSubBase, { fontSize: isMobile ? 12 : 13 }],
  categoryPill: (isMobile: boolean, active: boolean) => ({
    backgroundColor: active ? "#f4511e" : "#f7f9fc",
    paddingHorizontal: isMobile ? 14 : 16,
    paddingVertical: isMobile ? 8 : 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: active ? "#f4511e" : "#d5deeb",
  }),
  categoryText: (isMobile: boolean, active: boolean) => [styles.categoryTextBase, { color: active ? "#fff" : "#334155", fontSize: isMobile ? 13 : 14 }],
  menuListPad: (isMobile: boolean) => [{ padding: isMobile ? 14 : 20, gap: isMobile ? 12 : 14 }, styles.menuListPadBase],
  emptyMenuText: (isMobile: boolean) => [styles.emptyMenuTextBase, { fontSize: isMobile ? 14 : 16 }],
  emptyMenuTextWithMargin: (isMobile: boolean) => [styles.emptyMenuTextBase, { marginTop: 10, fontSize: isMobile ? 13 : 14 }],
  checkoutTitle: (isMobile: boolean) => [styles.checkoutTitleBase, { fontSize: isMobile ? 20 : 24 }],
  orderCard: (isMobile: boolean) => [styles.orderCardBase, { padding: isMobile ? 14 : 16, gap: isMobile ? 10 : 12 }],
  orderCardTitle: (isMobile: boolean) => [styles.orderCardTitleBase, { fontSize: isMobile ? 16 : 18 }],
  orderItemName: (isMobile: boolean) => [styles.orderItemNameBase, { fontSize: isMobile ? 14 : 15 }],
  orderItemPrice: (isMobile: boolean) => [styles.orderItemPriceBase, { fontSize: isMobile ? 14 : 15 }],
  successIconWrap: (isMobile: boolean) => [styles.successIconWrapBase, { width: isMobile ? 80 : 100, height: isMobile ? 80 : 100, borderRadius: (isMobile ? 80 : 100) / 2 }],
  successIconText: (isMobile: boolean) => ({ fontSize: isMobile ? 40 : 50 }),
  successTitle: (isMobile: boolean) => [styles.successTitleBase, { fontSize: isMobile ? 22 : 28 }],
  successSubtitle: (isMobile: boolean) => [styles.successSubtitleBase, { fontSize: isMobile ? 14 : 16 }],
  successOrderIdText: (isMobile: boolean) => [styles.successOrderIdTextBase, { fontSize: isMobile ? 16 : 18 }],
  successEta: (isMobile: boolean) => [styles.successEtaBase, { fontSize: isMobile ? 13 : 15 }],
  orderMoreBtn: (isMobile: boolean, hovered: boolean, pressed: boolean) => ({
    backgroundColor: hovered ? "#d73f11" : "#f4511e",
    paddingHorizontal: isMobile ? 28 : 36,
    paddingVertical: isMobile ? 14 : 16,
    borderRadius: 14,
    transform: [{ scale: pressed ? 0.98 : 1 }],
  }),
  orderMoreText: (isMobile: boolean) => [styles.orderMoreTextBase, { fontSize: isMobile ? 16 : 18 }],
};

export const foodOrderScreenColors = {
  placeholder: "#96a0b2",
  spinner: "#f4511e",
} as const;
