import { StyleSheet } from "react-native";

export const homeLayoutStyles = {
  panelWithTop: (paddingTop: number) => ({ flex: 1, paddingTop }),
  rescueScrollContent: (paddingTop: number) => ({ paddingTop, paddingBottom: 24 }),
  topPadding: (paddingTop: number) => ({ paddingTop }),
  festivalBadgeBackground: (color?: string) => ({ backgroundColor: color ? `${color}22` : "rgba(0,0,0,0.08)" }),
};

export const homeScreenColors = {
  loadingAccent: "#0f1a2d",
  spinnerLight: "#fff",
} as const;

export const styles = StyleSheet.create({
  flexOnly: {
    flex: 1,
  },
  flexTransparent: {
    flex: 1,
    backgroundColor: "transparent",
  },
  overlayFill: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 1,
  },
  centerTransparent: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "transparent",
  },
  loadingCaption: {
    color: "#fff",
    marginTop: 8,
  },
  emptyStateWrap: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 24,
    backgroundColor: "transparent",
  },
  emptyStateTitle: {
    color: "#fff",
    fontSize: 18,
    textAlign: "center",
  },
  emptyStateError: {
    color: "#ff6b6b",
    fontSize: 12,
    marginTop: 10,
    textAlign: "center",
  },
  retryButton: {
    marginTop: 14,
    borderWidth: 1,
    borderColor: "#333",
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 8,
  },
  retryButtonText: {
    color: "#fff",
    fontWeight: "700",
  },
  userNotice: {
    position: "absolute",
    right: 16,
    top: 86,
    zIndex: 2000,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#1f7a34",
    backgroundColor: "rgba(9, 30, 14, 0.92)",
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  userNoticeText: {
    color: "#d9ffe3",
    fontWeight: "700",
    fontSize: 13,
  },
  travelRoot: {
    flex: 1,
    backgroundColor: "#ffffff",
    position: "relative",
  },
  travelOverlay: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    backgroundColor: "rgba(255,255,255,0.4)",
  },
  travelContentWrap: {
    flex: 1,
  },
  travelContent: {
    paddingTop: 110,
    paddingHorizontal: 18,
    paddingBottom: 120,
  },
  hero: {
    backgroundColor: "#ffffff",
    borderRadius: 18,
    padding: 16,
    borderWidth: 1,
    borderColor: "#e6e6e6",
  },
  heroTitle: {
    fontSize: 26,
    fontWeight: "800",
    color: "#000000",
  },
  heroSub: {
    marginTop: 6,
    color: "#333333",
    fontSize: 13.5,
  },
  alertCard: {
    borderWidth: 1,
    borderColor: "#ff5d5d",
    backgroundColor: "#fff3f3",
    borderRadius: 14,
    padding: 14,
    marginTop: 12,
  },
  alertTitle: {
    fontWeight: "800",
    color: "#b42318",
    marginBottom: 6,
  },
  alertText: {
    color: "#7a1b1b",
    fontSize: 12.5,
  },
  section: {
    marginTop: 18,
  },
  sectionTitle: {
    fontSize: 22,
    fontWeight: "800",
    color: "#000000",
  },
  sectionSub: {
    color: "#333333",
    marginTop: 6,
  },
  sliderSection: {
    marginTop: 16,
  },
  sliderTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: "#000000",
  },
  sliderRow: {
    paddingVertical: 12,
    paddingRight: 12,
    gap: 12,
  },
  sliderCard: {
    width: 265,
    borderWidth: 1,
    borderColor: "#e6e6e6",
    backgroundColor: "#ffffff",
    borderRadius: 18,
    padding: 16,
    shadowColor: "#0f172a",
    shadowOpacity: 0.06,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 2,
  },
  festivalCard: {
    width: 285,
  },
  festivalImage: {
    width: "100%",
    height: 130,
    borderRadius: 10,
    marginBottom: 10,
    backgroundColor: "#e5e7eb",
  },
  festivalBadgeRow: {
    alignSelf: "flex-start",
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.08)",
    paddingHorizontal: 10,
    paddingVertical: 4,
    marginBottom: 8,
  },
  festivalMonth: {
    color: "#111827",
    fontSize: 11,
    fontWeight: "800",
  },
  festivalLocation: {
    marginTop: 6,
    color: "#334155",
    fontSize: 12.5,
    fontWeight: "700",
  },
  sliderCardImage: {
    width: "100%",
    height: 115,
    borderRadius: 10,
    marginBottom: 10,
    backgroundColor: "#e5e7eb",
  },
  sliderCardImagePlaceholder: {
    width: "100%",
    height: 115,
    borderRadius: 10,
    marginBottom: 10,
    backgroundColor: "#f1f5f9",
    alignItems: "center",
    justifyContent: "center",
  },
  sliderCardImagePlaceholderText: {
    color: "#64748b",
    fontSize: 11,
    fontWeight: "600",
  },
  sliderBadge: {
    alignSelf: "flex-start",
    backgroundColor: "#34e0a1",
    color: "#000000",
    fontSize: 11,
    fontWeight: "800",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
    marginBottom: 8,
  },
  sliderCardTitle: {
    fontSize: 15,
    fontWeight: "800",
    color: "#000000",
  },
  sliderCardDesc: {
    marginTop: 6,
    color: "#333333",
    fontSize: 12.5,
  },
  sliderCardPrice: {
    marginTop: 8,
    fontWeight: "800",
    color: "#000000",
  },
  sliderCta: {
    marginTop: 12,
    alignSelf: "flex-start",
    borderWidth: 0,
    backgroundColor: "#000000",
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  sliderCtaText: {
    color: "#ffffff",
    fontSize: 12,
    fontWeight: "800",
  },
  cardGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginHorizontal: -6,
    marginTop: 12,
  },
  serviceCard: {
    flexGrow: 1,
    flexBasis: 220,
    borderWidth: 1,
    borderColor: "#d9e7df",
    backgroundColor: "#ffffff",
    borderRadius: 14,
    padding: 14,
    margin: 6,
    shadowColor: "#0f172a",
    shadowOpacity: 0.08,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
    elevation: 2,
  },
  serviceTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: "#1f2a24",
  },
  serviceCount: {
    marginTop: 6,
    fontSize: 12,
    fontWeight: "800",
    color: "#0f5b3f",
  },
  serviceDesc: {
    marginTop: 8,
    color: "#5f6e66",
    fontSize: 12.5,
  },
  serviceCta: {
    marginTop: 12,
    alignSelf: "flex-start",
    borderWidth: 1,
    borderColor: "#00a568",
    backgroundColor: "#eef8f3",
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  serviceCtaText: {
    color: "#134935",
    fontSize: 12,
    fontWeight: "800",
  },
  loadingRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingVertical: 12,
  },
  loadingText: {
    color: "#1f2a24",
    fontWeight: "600",
  },
  emptyCard: {
    borderWidth: 1,
    borderColor: "#d9e7df",
    backgroundColor: "#ffffff",
    borderRadius: 14,
    padding: 16,
    marginTop: 12,
  },
  emptyTitle: {
    fontWeight: "800",
    color: "#1f2a24",
    marginBottom: 6,
  },
  emptyText: {
    color: "#5f6e66",
    fontSize: 12.5,
  },
  featureGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginHorizontal: -6,
    marginTop: 12,
  },
  featureCard: {
    flexGrow: 1,
    flexBasis: 240,
    borderWidth: 1,
    borderColor: "#d9e7df",
    backgroundColor: "#ffffff",
    borderRadius: 14,
    padding: 14,
    margin: 6,
    shadowColor: "#0f172a",
    shadowOpacity: 0.08,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
    elevation: 2,
  },
  featureBadge: {
    alignSelf: "flex-start",
    backgroundColor: "#e6f6ef",
    color: "#0f5b3f",
    fontSize: 11,
    fontWeight: "800",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
    marginBottom: 8,
  },
  featureTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: "#1f2a24",
  },
  featureDesc: {
    marginTop: 6,
    color: "#5f6e66",
    fontSize: 12.5,
  },
  featurePrice: {
    marginTop: 8,
    fontWeight: "800",
    color: "#0f5b3f",
  },
  featureBtn: {
    marginTop: 12,
    borderRadius: 10,
    backgroundColor: "#00aa6c",
    paddingVertical: 8,
    alignItems: "center",
  },
  featureBtnText: {
    color: "#ffffff",
    fontWeight: "800",
  },
  martRoot: {
    flex: 1,
    backgroundColor: "#f5f5f5",
  },
  martDesktopLayout: {
    flex: 1,
    flexDirection: "row",
  },
  martCategoryRail: {
    width: 240,
    borderRightWidth: 1,
    borderRightColor: "#e2e8f0",
    backgroundColor: "#f8fafc",
  },
  martCategoryRailContent: {
    paddingVertical: 10,
  },
  martCategoryItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 12,
    paddingVertical: 12,
    borderLeftWidth: 3,
    borderLeftColor: "transparent",
  },
  martCategoryItemActive: {
    backgroundColor: "#efe3ff",
    borderLeftColor: "#a855f7",
  },
  martCategoryImage: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: "#e2e8f0",
  },
  martCategoryText: {
    flex: 1,
    color: "#334155",
    fontSize: 15,
    fontWeight: "600",
  },
  martCategoryTextActive: {
    color: "#7e22ce",
    fontWeight: "700",
  },
  martProductsPane: {
    flex: 1,
  },
  martProductsPaneContent: {
    paddingHorizontal: 16,
    paddingBottom: 130,
    paddingTop: 14,
  },
  martGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginHorizontal: -6,
  },
  martGridMobile: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginHorizontal: -6,
    marginTop: 8,
  },
  martCard: {
    width: 184,
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#e2e8f0",
    borderRadius: 12,
    padding: 10,
    margin: 6,
  },
  martProductImage: {
    width: "100%",
    height: 118,
    borderRadius: 8,
    backgroundColor: "#f1f5f9",
  },
  martAddButton: {
    position: "absolute",
    right: 12,
    top: 110,
    borderWidth: 1.5,
    borderColor: "#f43f5e",
    borderRadius: 10,
    backgroundColor: "#ffffff",
    paddingHorizontal: 14,
    paddingVertical: 5,
  },
  martAddButtonText: {
    color: "#f43f5e",
    fontWeight: "800",
    fontSize: 13,
  },
  martPriceRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginTop: 12,
  },
  martPrice: {
    backgroundColor: "#1f8f3a",
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "800",
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  martOriginalPrice: {
    color: "#64748b",
    fontSize: 12,
    fontWeight: "700",
    textDecorationLine: "line-through",
  },
  martDiscount: {
    marginTop: 4,
    color: "#15803d",
    fontSize: 11,
    fontWeight: "800",
  },
  martProductTitle: {
    marginTop: 8,
    color: "#0f172a",
    fontSize: 15,
    fontWeight: "700",
    minHeight: 38,
  },
  martProductPack: {
    marginTop: 4,
    color: "#475569",
    fontSize: 12,
    fontWeight: "500",
  },
  martTag: {
    alignSelf: "flex-start",
    marginTop: 7,
    borderRadius: 8,
    backgroundColor: "#dbeafe",
    color: "#1d4ed8",
    fontSize: 11,
    fontWeight: "700",
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  martRating: {
    marginTop: 8,
    color: "#166534",
    fontSize: 12,
    fontWeight: "700",
  },
  martMobileWrap: {
    flex: 1,
  },
  martMobileContent: {
    paddingHorizontal: 10,
    paddingBottom: 130,
    paddingTop: 8,
  },
  martCategoryRow: {
    paddingVertical: 6,
    paddingRight: 10,
  },
  martCategoryChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderWidth: 1,
    borderColor: "#d1d5db",
    borderRadius: 999,
    paddingVertical: 8,
    paddingHorizontal: 10,
    backgroundColor: "#ffffff",
    marginRight: 8,
  },
  martCategoryChipActive: {
    borderColor: "#a855f7",
    backgroundColor: "#f3e8ff",
  },
  martCategoryChipImage: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: "#e2e8f0",
  },
  martCategoryChipText: {
    color: "#334155",
    fontWeight: "600",
    fontSize: 13,
  },
  martCategoryChipTextActive: {
    color: "#7e22ce",
    fontWeight: "700",
  },
});
