import { StyleSheet } from "react-native";

export const myOrdersStyles = StyleSheet.create({
  loadingWrap: { flex: 1, alignItems: "center", justifyContent: "center", backgroundColor: "transparent" },
  loadingText: { color: "#6b7280", marginTop: 8 },
  root: { flex: 1, backgroundColor: "transparent" },
  header: {
    margin: 14,
    marginBottom: 10,
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderWidth: 1,
    borderColor: "#1d3258",
    backgroundColor: "#0f1a2d",
    borderRadius: 16,
  },
  headerTitle: { color: "#fff", fontWeight: "800", fontSize: 20 },
  headerSub: { color: "#9db0d6", fontSize: 12, marginTop: 2 },
  filtersRow: { flexDirection: "row", paddingHorizontal: 16, paddingBottom: 10, gap: 8, flexWrap: "wrap" },
  filterPill: { paddingHorizontal: 14, paddingVertical: 6, borderRadius: 16, borderWidth: 1 },
  filterText: { fontSize: 13, fontWeight: "700" },
  errorWrap: { padding: 16 },
  errorText: { color: "#ef4444", fontSize: 13 },
  retryBtn: {
    marginTop: 10,
    paddingVertical: 8,
    paddingHorizontal: 14,
    backgroundColor: "#fff",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#d5deeb",
    alignSelf: "flex-start",
  },
  retryText: { color: "#f4511e", fontWeight: "700" },
  list: { flex: 1 },
  listContent: { padding: 16, gap: 12, paddingBottom: 40 },
  emptyWrap: { alignItems: "center", paddingVertical: 60 },
  emptyText: { color: "#6b7280", fontSize: 15, textAlign: "center" },
  card: {
    backgroundColor: "#fff",
    borderRadius: 12,
    overflow: "hidden",
    shadowOffset: { width: 0, height: 3 },
  },
  cardHeader: { padding: 14, flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  cardHeaderMain: { flex: 1, marginRight: 10 },
  cardTitle: { color: "#111827", fontWeight: "700", fontSize: 14 },
  cardMeta: { color: "#7c8698", fontSize: 11, marginTop: 2 },
  cardHeaderRight: { flexDirection: "row", alignItems: "center", gap: 6 },
  amountText: { color: "#f4511e", fontWeight: "800", fontSize: 13 },
  statusBadge: { paddingHorizontal: 8, paddingVertical: 3, borderRadius: 10 },
  statusText: { fontSize: 11, fontWeight: "700" },
  expandedWrap: { padding: 14, paddingTop: 0, borderTopWidth: 1, borderTopColor: "#edf1f7" },
  rawWrap: { backgroundColor: "#f8fafc", borderWidth: 1, borderColor: "#e4eaf3", borderRadius: 8, padding: 10, marginTop: 8 },
  rawText: { color: "#5f6b81", fontSize: 11, fontFamily: "monospace" },
  actionsRow: { flexDirection: "row", gap: 8, marginTop: 12, flexWrap: "wrap" },
  refundBtn: { backgroundColor: "#fff5f5", paddingHorizontal: 14, paddingVertical: 8, borderRadius: 8, borderWidth: 1, borderColor: "#ef4444" },
  refundText: { color: "#ef4444", fontWeight: "700", fontSize: 12 },
  rateBtn: { backgroundColor: "#fff7ed", paddingHorizontal: 14, paddingVertical: 8, borderRadius: 8, borderWidth: 1, borderColor: "#f59e0b" },
  rateText: { color: "#f59e0b", fontWeight: "700", fontSize: 12 },
});

export const myOrdersDynamicStyles = {
  filterPill: (active: boolean) => ({
    backgroundColor: active ? "#f4511e" : "#ffffff",
    borderColor: active ? "#f4511e" : "#d5deeb",
  }),
  filterText: (active: boolean) => ({ color: active ? "#fff" : "#334155" }),
  cardState: (expanded: boolean) => ({
    borderWidth: 1,
    borderColor: expanded ? "#f4511e" : "#d5deeb",
    shadowColor: expanded ? "#f4511e" : "#1d2c49",
    shadowOpacity: expanded ? 0.15 : 0.07,
    shadowRadius: 8,
    elevation: expanded ? 4 : 2,
  }),
  statusBadge: (statusColor: string) => ({ backgroundColor: `${statusColor}22` }),
  statusText: (statusColor: string) => ({ color: statusColor }),
};

export const myOrdersColors = {
  spinner: "#f4511e",
  refreshTint: "#f4511e",
} as const;
