import { Animated, Platform, StyleSheet } from "react-native";

export const portfolioCarouselDynamicStyles: Record<string, (...args: any[]) => any> = {
  heroImage: (w: number, heroHeight: number, windowHeight: number) => ({
    width: w,
    height: heroHeight || windowHeight,
    backgroundColor: "#111",
  }),
  heroScrimBottom: (isMobile: boolean, width: string) => ({
    width,
    bottom: 0,
    top: isMobile ? 0 : 80,
    paddingTop: isMobile ? 12 : 24,
    paddingHorizontal: isMobile ? 10 : 16,
    paddingBottom: isMobile ? 12 : 16,
    backgroundColor: isMobile ? "rgba(0, 0, 0, .65)" : "rgba(0, 0, 0, 0.87)",
    justifyContent: isMobile ? "flex-end" : "center",
  }),
  textSize: (fontSize: number) => ({ fontSize }),
  heroActionsInline: (isMobile: boolean) => ({
    flexDirection: isMobile ? "column" : "row",
    marginTop: 10,
  }),
  buttonWidth: (width: number) => ({ width }),
  thumbContainer: (isMobile: boolean) => ({
    height: isMobile ? 100 : 150,
    marginBottom: isMobile ? 90 : 0,
  }),
  thumbEdgePosition: (thumbH: number, edgeButton: number) => ({
    top: 8 + (thumbH / 2),
    marginTop: -(edgeButton / 2),
  }),
  thumbEdgeButton: (edgeButton: number, hovered: boolean, pressed: boolean) => ({
    width: edgeButton,
    height: edgeButton,
    borderRadius: edgeButton / 2,
    backgroundColor: hovered ? "#007c00" : "rgba(0,0,0,0.45)",
    borderColor: hovered ? "#007c00" : "rgba(255,255,255,0.6)",
    opacity: pressed ? 0.92 : 1,
  }),
  thumbEdgeArrow: (isMobile: boolean) => ({ fontSize: isMobile ? 20 : 28 }),
  thumbContent: (edgeInset: number) => ({ paddingHorizontal: edgeInset, alignItems: "center" }),
  thumbSize: (thumbW: number, thumbH: number) => ({ width: thumbW, height: thumbH }),
  thumbMeta: (edgeInset: number) => ({ marginHorizontal: edgeInset }),
  hoverText: (hovered: boolean) => (hovered ? { color: "#fff" } : null),
  hoverScaleWrap: (scale: Animated.Value) => ({ transform: [{ scale }] }),
};


export const portfolioCarouselStyles = StyleSheet.create({
  heroScrimTop: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: 110,
    backgroundColor: "transparent",
  },
  heroScrimBottom: {
    position: "absolute",
    left: 0,
    top: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.75)",
    justifyContent: "center",
  },
  rightPanelContent: {
    flexGrow: 1,
    justifyContent: "center",
  },
  heroTopRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    marginBottom: 12,
    gap: 6,
    flexWrap: "wrap",
  },
  heroPill: {
    backgroundColor: "#f5f2e8",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
  },
  heroPillText: {
    color: "#1c1c1c",
    fontWeight: "800",
    letterSpacing: 0.3,
  },
  heroPillGhost: {
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.55)",
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 999,
  },
  heroPillGhostText: {
    color: "#fff",
    fontWeight: "700",
    letterSpacing: 0.2,
  },
  heroPillPrice: {
    backgroundColor: "#f5f2e8",
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 999,
  },
  heroPillPriceText: {
    color: "#1c1c1c",
    fontWeight: "700",
    letterSpacing: 0.2,
  },
  heroPillDropped: {
    borderWidth: 1,
    borderColor: "#f59e0b",
    backgroundColor: "rgba(245, 158, 11, 0.16)",
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 999,
  },
  heroPillDroppedText: {
    color: "#fcd34d",
    fontWeight: "800",
    letterSpacing: 0.2,
  },
  heroPillAvailable: {
    borderWidth: 1,
    borderColor: "#22c55e",
    backgroundColor: "rgba(34, 197, 94, 0.16)",
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 999,
  },
  heroPillAvailableText: {
    color: "#bbf7d0",
    fontWeight: "800",
    letterSpacing: 0.2,
  },
  heroPillUnavailable: {
    borderWidth: 1,
    borderColor: "#ef4444",
    backgroundColor: "rgba(239, 68, 68, 0.14)",
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 999,
  },
  heroPillUnavailableText: {
    color: "#fecaca",
    fontWeight: "800",
    letterSpacing: 0.2,
  },
  heroTitle: {
    color: "#fff",
    fontWeight: "800",
    letterSpacing: 0.2,
    textAlign: "left",
    marginTop: 4,
    ...Platform.select({
      web: { textShadow: "0px 2px 8px rgba(0, 0, 0, 0.8)" },
      default: {
        textShadowColor: "rgba(0, 0, 0, 0.8)",
        textShadowOffset: { width: 0, height: 2 },
        textShadowRadius: 8,
      },
    }),
  },
  heroDesc: {
    color: "rgba(255,255,255,0.88)",
    lineHeight: 18,
    marginTop: 6,
    textAlign: "left",
    ...Platform.select({
      web: { textShadow: "0px 1px 6px rgba(0, 0, 0, 0.7)" },
      default: {
        textShadowColor: "rgba(0, 0, 0, 0.7)",
        textShadowOffset: { width: 0, height: 1 },
        textShadowRadius: 6,
      },
    }),
  },
  heroOldPrice: {
    color: "rgba(255,255,255,0.65)",
    textDecorationLine: "line-through",
    marginTop: 4,
  },
  heroMetaLine: {
    color: "rgba(255,255,255,0.8)",
    marginTop: 4,
    textAlign: "left",
  },
  heroHighlightLine: {
    fontWeight: "800",
  },
  heroMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    marginTop: 8,
    gap: 10,
  },
  heroPrice: {
    color: "#fff",
    fontWeight: "700",
    ...Platform.select({
      web: { textShadow: "0px 1px 6px rgba(0, 0, 0, 0.7)" },
      default: {
        textShadowColor: "rgba(0, 0, 0, 0.7)",
        textShadowOffset: { width: 0, height: 1 },
        textShadowRadius: 6,
      },
    }),
  },
  heroCount: {
    color: "rgba(255,255,255,0.7)",
    fontWeight: "600",
  },
  heroActionsInline: {
    marginTop: 10,
    gap: 8,
  },
  galleryList: {
    marginTop: 8,
    maxHeight: 200,
    borderWidth: 1,
    borderColor: "#1f1f1f",
    borderRadius: 10,
    padding: 6,
    backgroundColor: "rgba(0,0,0,0.35)",
  },
  galleryCard: {
    borderWidth: 1,
    borderColor: "#1f1f1f",
    borderRadius: 8,
    overflow: "hidden",
    backgroundColor: "#0d0d0d",
    marginBottom: 8,
  },
  galleryImage: {
    width: "100%",
    height: 90,
  },
  galleryImageEmpty: {
    height: 90,
    backgroundColor: "#111",
    alignItems: "center",
    justifyContent: "center",
  },
  galleryMeta: {
    padding: 6,
    gap: 2,
  },
  galleryTitle: {
    color: "#fff",
    fontWeight: "700",
  },
  galleryPrice: {
    color: "rgba(255,255,255,0.75)",
  },
  galleryOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.74)",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 50,
    padding: 16,
  },
  galleryModal: {
    width: "100%",
    maxWidth: 980,
    backgroundColor: "#0d0d0d",
    borderWidth: 1,
    borderColor: "#222",
    borderRadius: 14,
    padding: 12,
  },
  galleryCloseBtn: {
    position: "absolute",
    top: 10,
    right: 10,
    width: 32,
    height: 32,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.5)",
    backgroundColor: "rgba(0,0,0,0.45)",
    zIndex: 3,
  },
  galleryCloseText: {
    color: "#fff",
    fontSize: 13,
    fontWeight: "800",
  },
  galleryModalTitle: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "800",
    marginBottom: 10,
    paddingRight: 40,
  },
  galleryHeroWrap: {
    width: "100%",
    aspectRatio: 16 / 9,
    borderRadius: 10,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#1f1f1f",
    backgroundColor: "#111",
  },
  galleryHeroImage: {
    width: "100%",
    height: "100%",
  },
  galleryHeroFallback: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  galleryThumbRow: {
    paddingTop: 10,
    gap: 8,
  },
  galleryThumbWrap: {
    width: 108,
    height: 72,
    borderRadius: 8,
    overflow: "hidden",
    borderWidth: 2,
    borderColor: "transparent",
  },
  galleryThumbActive: {
    borderColor: "#fff",
  },
  galleryThumbImage: {
    width: "100%",
    height: "100%",
  },
  bookButton: {
    backgroundColor: "#f5f2e8",
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 12,
    alignItems: "center",
    alignSelf: "flex-start",
  },
  bookButtonText: {
    color: "#1c1c1c",
    fontWeight: "800",
  },
  bookButtonDisabled: {
    backgroundColor: "rgba(120,120,120,0.7)",
    borderColor: "rgba(170,170,170,0.8)",
  },
  bookButtonTextDisabled: {
    color: "#f3f4f6",
  },
  viewButton: {
    borderColor: "#fff",
    borderWidth: 2,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 12,
    alignItems: "center",
    alignSelf: "flex-start",
    backgroundColor: "rgba(0,0,0,0.25)",
  },
  viewButtonText: {
    color: "#fff",
    fontWeight: "700",
  },
  storeBadgesRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 8,
    flexWrap: "wrap",
  },
  storeBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.35)",
    backgroundColor: "rgba(0,0,0,0.45)",
  },
  storeIconBubble: {
    width: 24,
    height: 24,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
  },
  storeIconApple: {
    backgroundColor: "#111",
  },
  storeIconPlay: {
    backgroundColor: "#0b6a2b",
  },
  storeIconText: {
    color: "#fff",
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 0.2,
  },
  storeBadgeSubText: {
    color: "rgba(255,255,255,0.78)",
    fontSize: 9,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.4,
    lineHeight: 11,
  },
  storeBadgeText: {
    color: "#fff",
    fontSize: 13,
    fontWeight: "800",
    letterSpacing: 0.2,
  },
  thumbContainer: {
    paddingVertical: 8,
    paddingHorizontal: 8,
    backgroundColor: "transparent",
  },
  thumbWrap: {
    marginHorizontal: 6,
    borderRadius: 6,
    overflow: "hidden",
    borderWidth: 2,
    borderColor: "transparent",
  },
  thumbActive: {
    borderColor: "#fff",
  },
  thumb: {
    backgroundColor: "#111",
  },
  thumbEdgeLeft: {
    position: "absolute",
    left: 8,
    top: "50%",
    alignItems: "center",
    zIndex: 5,
  },
  thumbEdgeRight: {
    position: "absolute",
    right: 8,
    top: "50%",
    alignItems: "center",
    zIndex: 5,
  },
  thumbEdgeButton: {
    borderWidth: 2,
    alignItems: "center",
    justifyContent: "center",
  },
  thumbEdgeArrow: {
    color: "#fff",
    fontWeight: "800",
  },
  thumbEdgeLabel: {
    marginTop: 6,
    color: "#fff",
    fontWeight: "700",
    fontSize: 12,
    textAlign: "center",
    ...Platform.select({
      web: { textShadow: "0px 1px 3px rgba(0,0,0,0.6)" },
      default: {
        textShadowColor: "rgba(0,0,0,0.6)",
        textShadowOffset: { width: 0, height: 1 },
        textShadowRadius: 3,
      },
    }),
  },
  thumbMeta: {
    marginTop: 6,
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 6,
  },
  thumbTitle: {
    color: "#fff",
    fontWeight: "800",
    textAlign: "center",
  },
  thumbPrice: {
    color: "#f5f2e8",
    fontWeight: "800",
    marginTop: 2,
    textAlign: "center",
  },
  root: {
    flex: 1,
    backgroundColor: "transparent",
  },
  flex1: {
    flex: 1,
  },
  galleryHeroFallbackText: {
    color: "#777",
  },
  hoverButton: {
    backgroundColor: "#007c00",
    borderColor: "#007c00",
  },
  hoverText: {
    color: "#fff",
  },
});
