import { Animated, Platform, StyleSheet } from "react-native";

export const topNavStyles = StyleSheet.create({
  absoluteFill: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  mobileContainer: {
    position: "absolute",
    top: 8,
    left: 8,
    right: 8,
    zIndex: 100,
  },
  mobileCard: {
    backgroundColor: "rgba(16, 16, 16, 0.95)",
    borderColor: "rgba(245, 242, 232, 0.1)",
    borderWidth: 1,
    borderRadius: 16,
    padding: 10,
    gap: 8,
  },
  mobileHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  mobileIconRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  logoWrap: {
    position: "relative",
  },
  logoCircleMobile: {
    width: 46,
    height: 46,
    borderRadius: 999,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
  logoCircleDesktop: {
    borderRadius: 999,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
  logoSizeMobile: {
    width: 42,
    height: 28,
  },
  evTextMobile: {
    position: "absolute",
    left: "100%",
    color: "#fff",
    fontSize: 18,
    fontWeight: "900",
    letterSpacing: 0.5,
    textShadowColor: "rgba(245,242,232,0.7)",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  evTextDesktop: {
    position: "absolute",
    color: "#fff",
    fontSize: 18,
    fontWeight: "900",
    letterSpacing: 0.5,
    textShadowColor: "rgba(245,242,232,0.7)",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  flex1: {
    flex: 1,
  },
  mobileAuthBtn: {
    marginLeft: 8,
    paddingHorizontal: 12.5,
    paddingVertical: 7.5,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(245, 242, 232, 0.2)",
    backgroundColor: "rgba(245, 242, 232, 0.1)",
  },
  mobilePrimaryRow: {
    flexDirection: "row",
    gap: 6,
    justifyContent: "center",
  },
  mobileFilterDock: {
    position: "absolute",
    left: 8,
    right: 8,
    bottom: 8,
    zIndex: 120,
  },
  mobileFilterCard: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 6,
    backgroundColor: "rgba(16, 16, 16, 0.95)",
    borderColor: "rgba(245, 242, 232, 0.15)",
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 8,
  },
  desktopOuter: {
    paddingHorizontal: 14,
    paddingTop: 10,
    paddingBottom: 8,
    gap: 10,
    backgroundColor: "transparent",
  },
  desktopBar: {
    flexDirection: "row",
    alignItems: "center",
    gap: 9.375,
    backgroundColor: "#101010",
    borderColor: "#1f1f1f",
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 11.25,
    paddingVertical: 7.5,
    shadowColor: "transparent",
    shadowOpacity: 0,
    shadowRadius: 0,
    shadowOffset: { width: 0, height: 0 },
    elevation: 0,
    position: "relative",
  },
  desktopNavRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5.625,
  },
  desktopUserBtn: {
    paddingHorizontal: 11.25,
    paddingVertical: 7.5,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(158, 241, 166, 0.35)",
    backgroundColor: "rgba(25, 60, 32, 0.4)",
    maxWidth: 230,
  },
  desktopUserText: {
    color: "#9ef1a6",
    fontWeight: "700",
    fontSize: 14,
  },
  desktopIconBtnBase: {
    width: 38,
    height: 38,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(245, 242, 232, 0.2)",
    backgroundColor: "rgba(245, 242, 232, 0.08)",
    alignItems: "center",
    justifyContent: "center",
  },
  desktopAuthBtn: {
    paddingHorizontal: 11.25,
    paddingVertical: 7.5,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(245, 242, 232, 0.2)",
    backgroundColor: "transparent",
  },
  authTextBase: {
    color: "#fff",
    fontWeight: "700",
  },
  desktopFilterDock: {
    alignItems: "center",
    justifyContent: "center",
    marginTop: 4,
  },
  desktopFilterCard: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    backgroundColor: "#101010",
    borderColor: "#1f1f1f",
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 8,
  },
  hoverScaleWrap: {
    transform: [{ scale: 1 }],
  },
});

export const topNavDynamicStyles: Record<string, (...args: any[]) => any> = {
  mobileCardPlatform: () =>
    Platform.select({
      ios: { shadowColor: "#000", shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.3, shadowRadius: 12 },
      android: { elevation: 6 },
      web: { backdropFilter: "blur(20px)", boxShadow: "0 4px 24px rgba(0,0,0,0.3)" },
      default: {},
    }),
  mobileLogoCircle: (isMobile: boolean) => ({
    width: isMobile ? 46 : 56,
    height: isMobile ? 46 : 56,
  }),
  desktopLogoCircle: (isTablet: boolean) => ({
    width: isTablet ? 52 : 60,
    height: isTablet ? 52 : 60,
  }),
  desktopLogoSize: (isTablet: boolean) => ({
    width: isTablet ? 28 : 32,
    height: isTablet ? 28 : 32,
  }),
  evTextMobilePos: (isMobile: boolean) => ({
    top: isMobile ? -10 : -12,
    transform: [{ translateX: isMobile ? -10 : -11 }],
  }),
  evTextDesktopPos: (isTablet: boolean) => ({
    right: isTablet ? -6 : -7,
    top: isTablet ? -9 : -10,
    fontSize: isTablet ? 14 : 15,
  }),
  mobileAnimated: (navAnim: Animated.Value) => ({
    transform: [{ translateY: navAnim.interpolate({ inputRange: [0, 1], outputRange: [-50, 0] }) }],
    opacity: navAnim,
  }),
  mobileFilterAnimated: (navAnim: Animated.Value) => ({
    transform: [{ translateY: navAnim.interpolate({ inputRange: [0, 1], outputRange: [24, 0] }) }],
    opacity: navAnim,
  }),
  desktopAnimated: (navAnim: Animated.Value) => ({
    transform: [{ translateY: navAnim.interpolate({ inputRange: [0, 1], outputRange: [-12, 0] }) }],
    opacity: navAnim,
  }),
  mobileIconBtn: (hovered: boolean, pressed: boolean) => ({
    width: 34,
    height: 34,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: hovered ? "#f5f2e8" : "rgba(245, 242, 232, 0.2)",
    backgroundColor: hovered ? "#f5f2e8" : "rgba(245, 242, 232, 0.08)",
    alignItems: "center",
    justifyContent: "center",
    opacity: pressed ? 0.9 : 1,
  }),
  mobilePrimaryBtn: (active: boolean, hovered: boolean) => ({
    flex: 1,
    paddingHorizontal: 12.5,
    paddingVertical: 7.5,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: active ? "#f5f2e8" : "rgba(245, 242, 232, 0.2)",
    backgroundColor: active ? "#f5f2e8" : "transparent",
    alignItems: "center",
    ...(hovered ? { backgroundColor: "#007c00", borderColor: "#007c00" } : {}),
  }),
  mobilePrimaryText: (active: boolean, fontSize: number) => ({
    color: active ? "#1c1c1c" : "#fff",
    fontWeight: "700",
    fontSize,
  }),
  mobileFilterBtn: (active: boolean, pressed: boolean) => ({
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 8,
    paddingHorizontal: 6,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: active ? "#f5f2e8" : "rgba(245, 242, 232, 0.25)",
    backgroundColor: active ? "#f5f2e8" : "transparent",
    ...(pressed ? { opacity: 0.9 } : {}),
  }),
  mobileFilterText: (active: boolean) => ({
    color: active ? "#1c1c1c" : "#fff",
    fontWeight: "800",
    fontSize: 15,
  }),
  desktopPrimaryBtn: (active: boolean, isTablet: boolean) => ({
    paddingHorizontal: isTablet ? 10 : 11.25,
    paddingVertical: 7.5,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: active ? "#f5f2e8" : "transparent",
    backgroundColor: active ? "#f5f2e8" : "transparent",
  }),
  desktopPrimaryText: (active: boolean, fontSize: number) => ({
    color: active ? "#1c1c1c" : "#fff",
    fontWeight: "800",
    fontSize,
  }),
  desktopFilterBtn: (active: boolean, pressed: boolean) => ({
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: active ? "#f5f2e8" : "rgba(245, 242, 232, 0.25)",
    backgroundColor: active ? "#f5f2e8" : "transparent",
    ...(pressed ? { opacity: 0.9 } : {}),
  }),
  desktopFilterText: (active: boolean, fontSize: number) => ({
    color: active ? "#1c1c1c" : "#fff",
    fontWeight: "800",
    fontSize,
  }),
  authText: (fontSize: number) => ({
    color: "#fff",
    fontWeight: "700",
    fontSize,
  }),
  hoverText: (hovered: boolean) => (hovered ? { color: "#fff" } : null),
  hoverScaleWrap: (scale: Animated.Value) => ({ transform: [{ scale }] }),
  hoverScalePressable: (baseStyle: any, hovered: boolean) => [
    baseStyle,
    hovered ? { backgroundColor: "#007c00", borderColor: "#007c00" } : null,
  ],
};

export const topNavColors = {
  icon: "#fff",
} as const;
