export const bikeRentalScreenData = {
  datePicker: {
    styleId: "ev-bike-datepicker-style",
    className: "ev-bike-datepicker",
    popperClassName: "ev-bike-datepicker-popper",
    css: ".ev-bike-datepicker { width: 100%; border: 0; outline: none; font-weight: 600; color: #111; }\n.ev-bike-datepicker-popper { z-index: 3000 !important; }\n",
    dateFormat: "yyyy-MM-dd",
    startPlaceholder: "Start YYYY-MM-DD",
    endPlaceholder: "End YYYY-MM-DD",
  },
  header: {
    kicker: "BIKE",
    title: "Rent a Bike",
    subtitle: "Choose your bike, rental duration, and pickup time.",
  },
  loading: "Loading bikes\u2026",
  empty: "No bike rentals available yet.",
  labels: {
    available: "Available",
    maxRental: "Max rental",
    maxRentalSuffix: "day(s)",
    deposit: "Deposit",
    helmetIncluded: "Helmet included",
    image: "Image",
    bookingDetails: "Booking details",
    namePlaceholder: "Your name",
    phonePlaceholder: "Phone",
    qtyLabel: "How many bikes do you want to rent?",
    qtyPlaceholder: "How many bikes",
    startDate: "Start Date",
    endDate: "End Date",
    rentalDays: "Rental days:",
    total: "Estimated Total:",
    cancel: "Cancel",
    book: "Book Bike",
    booking: "Booking...",
  },
  notices: {
    selectBike: "Select a bike first.",
    endDateBefore: "End date cannot be before start date.",
    namePhoneRequired: "Enter your name and phone number.",
    maxDays: (days: number) => `Maximum rental for this bike is ${days} day(s).`,
    qtyUnavailable: "Selected quantity is not available.",
    bookingCreated: (id: string) => `Booking created. ID: ${id}`,
    bookingFailed: "Booking failed.",
  },
  api: {
    rentals: "/api/bike-rentals",
    booking: "/api/bike-bookings/book",
  },
  storageKeys: {
    name: "ev_bike_name",
    phone: "ev_bike_phone",
  },
  currency: {
    inr: "INR",
  },
  bikeFallback: "Bike",
  chevrons: {
    open: "\u25b2",
    closed: "\u25bc",
  },
};
