export const bookingModalData = {
  defaults: {
    guests: "1",
    numRooms: "1",
    checkIn: "2026-03-15",
    checkOut: "2026-03-18",
    tourDate: "2026-03-20",
    roomTypeFallback: "",
    maxGuestsFallback: 2,
    maxGuestsTourFallback: 99,
  },
  maxGuestsByRoom: {
    Hall: 4,
    Standard: 2,
    Deluxe: 2,
    Suite: 3,
    Presidential: 4,
  } as Record<string, number>,
  pricing: {
    pricePerRoom: 5000,
  },
  logs: {
    openWebPicker: "[BookingModal] openWebPicker called",
    openWebPickerValue: "[BookingModal] openWebPicker current value",
    webPickerChanged: "[BookingModal] web picker state changed",
  },
  labels: {
    imageFallback: "Image",
    bookPrefix: "Book:",
    close: "Close",
    gstNote: "GST is calculated server-side (Indian GST rules).",
    overview: "Overview",
    destination: "Destination:",
    location: "Location:",
    duration: "Duration:",
    previewUnavailable: "Preview unavailable",
    unavailable: "Unavailable",
    highlights: "Highlights",
    inclusions: "Inclusions",
    exclusions: "Exclusions",
    quickInfo: "Quick Info",
    itinerary: "Itinerary",
    amenities: "Amenities",
    bookingDetails: "Booking Details",
    guestInfo: "Guest Information",
    fullName: "Full Name",
    email: "Email",
    phoneNumber: "Phone Number",
    roomSelection: "Room Selection",
    roomType: "Room Type",
    numberOfRooms: "Number of Rooms",
    pricingTier: "Pricing Tier (Preview)",
    pricingTierNote: "Preview only. Final billing uses base pricing rules.",
    stayDates: "Stay Dates",
    checkIn: "Check In",
    checkOut: "Check Out",
    nights: "night",
    nightsPlural: "nights",
    room: "room",
    rooms: "rooms",
    roomsAvailable: (roomType: string) => `Rooms available for ${roomType}:`,
    minNights: "Min nights:",
    maxNights: "Max nights:",
    closedDates: "Selected dates are closed for this property.",
    guests: "Guests",
    maxCapacity: "Max capacity:",
    person: "person",
    people: "persons",
    tourDate: "Tour Date",
    tourDateHelp: "Tour Date (YYYY-MM-DD)",
    numberOfGuests: "Number of Guests",
    tourClosed: "Tour is closed on the selected date.",
    capacityForDate: (date: string) => `Capacity for ${date}:`,
    aadhaarCard: "Aadhaar Card",
    aadhaarRequired: "Required for all tour and hotel bookings.",
    uploadAadhaar: "Upload Aadhaar",
    replaceAadhaar: "Replace Aadhaar",
    uploading: "Uploading...",
    uploadedPrefix: "Uploaded:",
    aadhaarFallbackName: "Aadhaar card",
    aadhaarHint: "JPG/PNG only, max 5MB.",
    specialRequests: "Special Requests",
    specialRequestsPlaceholder: "Any special requirements...",
    offersPolicies: "Offers & Policies",
    coupons: "Coupons",
    cancellation: "Cancellation",
    submitted: (id: string) => `Submitted! ID: ${id}`,
    bookingSummary: "Booking Summary",
    total: "Total",
    preview: "Preview:",
    booking: "Booking...",
    confirmBooking: "Confirm Booking",
  },
  itinerary: {
    day: (value: number) => `Day ${value}`,
    activityJoiner: " <",
  },
  badges: {
    bullet: "\u2022",
    empty: "-",
  },
  icons: {
    calendar: "\ud83d\udcc5",
    info: "\u2139",
    plus: "+",
  },
  date: {
    webPlaceholder: "YYYY-MM-DD",
    tourDatePlaceholder: "YYYY-MM-DD",
    webPickerDays: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
    webPickerPrev: "<",
    webPickerNext: ">",
  },
  errors: {
    aadhaarWebOnly: "Aadhaar upload is available on web only right now.",
    loginRequired: "Please login with Google before placing a booking.",
    aadhaarRequired: "Please upload your Aadhaar card to continue.",
  },
  policy: {
    couponSeparator: "\u00b7",
    minPrefix: "Min",
    offSuffix: "off",
    hotelCancel: (hours: number, feePct: number) => `Free cancellation up to ${hours}h before check-in. Fee after: ${feePct}%.`,
    tourCancel: (hours: number, feePct: number) => `Free cancellation up to ${hours}h before departure. Fee after: ${feePct}%.`,
    currencySymbol: "\u20b9",
  },
  api: {
    bookings: "/api/bookings",
    meta: "/api/meta",
  },
  summary: {
    priceLine: (amount: number, nights: number, nightLabel: string) => `\u20b9${amount.toLocaleString()} \u00d7 ${nights} ${nightLabel}`,
    priceTotal: (value: number) => `\u20b9${value.toLocaleString()}`,
    roomsLine: (rooms: string, label: string) => `\u00d7 ${rooms} ${label}`,
    roomsCount: (rooms: string) => `\u00d7${rooms}`,
    tierLine: (name: string) => `Tier: ${name}`,
    percent: (value: number) => `${value}%`,
    totalPrice: (value: number) => `\u20b9${value.toLocaleString("en-IN")}`,
    previewPrice: (value: number) => `\u20b9${value.toLocaleString("en-IN")}`,
  },
  fields: {
    fileAccept: "image/jpeg,image/png",
    fileInputType: "file",
  },
  monthsLocale: "en-US",
};
