export const homeScreenData = {
  festivalColors: ["#1f4a6b", "#4f3d2b", "#3a5d3f", "#5a3f46", "#2f425d", "#5b4a2f"],
  martCategoryImages: {
    healthy_picks: "https://images.unsplash.com/photo-1623065422902-30a2d299bbe4?auto=format&fit=crop&w=120&q=80",
    oil: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=120&q=80",
    atta: "https://images.unsplash.com/photo-1514996937319-344454492b37?auto=format&fit=crop&w=120&q=80",
    dals_pulses: "https://images.unsplash.com/photo-1615485737651-e8f8e4e4d66c?auto=format&fit=crop&w=120&q=80",
    rice_more: "https://images.unsplash.com/photo-1586201375761-83865001e31b?auto=format&fit=crop&w=120&q=80",
    healthy_rice: "https://images.unsplash.com/photo-1516684732162-798a0062be99?auto=format&fit=crop&w=120&q=80",
    uncategorized: "https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=120&q=80",
  } as Record<string, string>,
  footerNav: [
    { key: "affiliate-program", label: "Affiliate Program", kind: "info" as const },
    { key: "contact-us", label: "Contact Us", kind: "info" as const },
    { key: "privacy-policy", label: "Privacy Policy", kind: "info" as const },
    { key: "refund-policy", label: "Refund Policy", kind: "info" as const },
    { key: "terms-and-conditions", label: "Terms and Conditions", kind: "info" as const },
    { key: "emergency", label: "Emergency", kind: "tab" as const },
  ],
  defaults: {
    uncategorized: "uncategorized",
    productName: "Product",
    festivalSeason: "All Season",
    festivalTitle: "Festival",
    festivalLocation: "Explore Valley",
    festivalVibe: "Live events and cultural experiences",
    festivalTicket: "On request",
  },
  errors: {
    toursUnavailable: "Tours unavailable",
    hotelsUnavailable: "Hotels unavailable",
    festivalsUnavailable: "Festivals unavailable",
    martUnavailable: "Mart unavailable",
    joiner: " | ",
  },
  htmlTemplate: (title: string, content: string) =>
    `<!doctype html><html><head><meta charset="utf-8" /><title>${title}</title></head><body>${content}</body></html>`,
  hero: {
    title: "ExploreValley",
    subtitle: "Plan trips, compare stays, and book local rides.",
    alertTitle: "We couldn't load everything.",
  },
  sections: {
    travelHighlights: "Travel Highlights",
    travelSub: "Swipe through travel services and curated stays.",
    toursTitle: "Tours",
    hotelsTitle: "Hotels",
    cottagesTitle: "Cottages",
    festivalsTitle: "Festivals",
  },
  loading: {
    tours: "Loading tours...",
    hotels: "Loading hotels...",
    cottages: "Loading cottages...",
    festivals: "Loading festivals...",
    app: "Loading ExploreValley...",
  },
  empty: {
    comingSoon: "Coming soon",
    noTours: "No tours yet",
    noHotels: "No hotels yet",
    noCottages: "No cottages yet",
    noFestivals: "No festivals yet",
    toursHelp: "Add tours from the admin panel or via Telegram.",
    hotelsHelp: "Add stays from the admin panel or via Telegram.",
    cottagesHelp: "Tag hotel listings with \"cottage\" to show them here.",
    festivalsHelp: "Add festival details from the admin panel or via Telegram.",
    syncPending: "Sync pending",
    upcomingSoon: "Upcoming soon",
  },
  badges: {
    tour: "Tour",
    hotel: "Hotel",
    cottage: "Cottage",
  },
  ctas: {
    bookNow: "Book now",
    bookStay: "Book stay",
    bookCottage: "Book cottage",
  },
  placeholders: {
    noImage: "No image",
  },
  pricing: {
    fromInr: (value: number | string) => `From INR ${value}`,
    fromInrWithBase: (value: number | string, base: number | string) => `From INR ${value} (INR ${base})`,
    fromInrNight: (value: number | string) => `From INR ${value}/night`,
    fromInrNightWithBase: (value: number | string, base: number | string) => `From INR ${value}/night (INR ${base})`,
  },
  mart: {
    add: "ADD",
    currency: "INR",
    off: "OFF",
  },
  countLabel: {
    loading: "Loading...",
    listedSuffix: "listed",
  },
  travelBackgroundUrl: "https://upload.wikimedia.org/wikipedia/commons/c/c3/Chandrakhani_Pass_Malana_Kullu.jpg",
  notifications: {
    title: "ExploreValley",
  },
  emptyState: {
    loadError: "We couldn't load ExploreValley right now. Please try again.",
    empty: "No content yet. Add tours/hotels from Admin Dashboard or via Telegram bot: /addtour or /addhotel",
    retry: "Retry",
    errorPrefix: "Load error:",
  },
  api: {
    tours: "/api/tours",
    hotels: "/api/hotels",
    restaurants: "/api/restaurants",
    buses: "/api/buses",
    meta: "/api/meta",
    festivals: "/api/festivals",
    martProducts: (martId?: string) =>
      martId ? `/api/mart-products?martId=${encodeURIComponent(martId)}` : "/api/mart-products",
    ordersStatus: "/api/orders/status",
    profile: "/api/profile",
    pages: (slug: string) => `/api/pages/${slug}`,
  },
};
