export const taxiScreenData = {
  datePicker: {
    styleId: "ev-datepicker-style",
    className: "ev-datepicker",
    popperClassName: "ev-datepicker-popper",
    css: ".ev-datepicker { width: 100%; border: 0; outline: none; font-weight: 600; color: #111; }\n.ev-datepicker-popper { z-index: 3000 !important; }\n",
    placeholder: "YYYY-MM-DD HH:mm",
    dateFormat: "yyyy-MM-dd HH:mm",
  },
  header: {
    kicker: "TAXI",
    title: "Book a Taxi",
    subtitle: "Choose your origin, destination, and time to see live rates.",
  },
  sections: {
    tripDetails: "Trip details",
    rates: "Rates",
  },
  loadingRoutes: "Loading routes\u2026",
  selectOrigin: "Select origin",
  selectDestination: "Select destination",
  selectOriginFirst: "Select origin first",
  dateTimeLabel: "Date & time",
  noRouteRates: "No rates available for this route.",
  noSelectionRates: "Select an origin and destination to view rates.",
  routeLabelFallback: "",
  booking: {
    title: "Confirm Booking",
    subtitle: "Please confirm selected cab and enter your details.",
    cabType: "Cab type",
    route: "Route",
    fare: "Fare",
    maxPeople: "Maximum people",
    maxPeopleSuffix: "person(s)",
    maxPeopleFallback: "As per vehicle capacity",
    peopleCount: "Number of people",
    peoplePlaceholder: "e.g. 2",
    name: "Name",
    namePlaceholder: "Your name",
    phone: "Phone",
    phonePlaceholder: "Phone number",
    cancel: "Cancel",
    confirm: "Confirm booking",
    confirmed: "Booking confirmed.",
  },
  rateCard: {
    na: "N/A",
    selected: "Selected",
    tapToSelect: "Tap to select",
  },
  dropdown: {
    noOptions: "No options",
  },
  errors: {
    namePhoneRequired: "Please enter your name and phone.",
    invalidPeople: "Please enter a valid number of people.",
    maxPeople: (max: number) => `Please choose up to ${max} people for this cab.`,
  },
  options: [
    { key: "ordinary4_1", label: "Ordinary 4+1", maxPeople: 5 },
    { key: "luxury4_1", label: "Luxury 4+1", maxPeople: 5 },
    { key: "ordinary6_1", label: "Ordinary 6+1", maxPeople: 7 },
    { key: "luxury6_1", label: "Luxury 6+1", maxPeople: 7 },
    { key: "traveller", label: "Traveller", maxPeople: null },
  ],
  api: {
    cabRates: "/api/cab-rates",
  },
  storageKeys: {
    name: "ev_taxi_name",
    phone: "ev_taxi_phone",
  },
  currency: {
    inr: "INR",
  },
};
